---

# ansible-playbook -i inventory/staging/ solr.yml

- hosts: solr
  gather_facts: true
  become: yes

  roles:
    - ansible-role-solr

  pre_tasks:
    - name: install python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      changed_when: false

    - name: install pre-reqs
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - openjdk-8-jre-headless
      tags:
        - solr

  tasks: []
